# Generated by Django 5.0.7 on 2025-11-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_Api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='h_users',
            name='password',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
