# Generated by Django 5.0.7 on 2025-11-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_Api', '0002_h_users_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='h_users',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
