# Generated by Django 5.0.7 on 2025-11-08 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_Api', '0003_alter_h_users_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='status',
        ),
    ]
