# Generated by Django 5.0.7 on 2025-11-11 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_Api', '0004_remove_room_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtestrequest',
            name='status',
        ),
    ]
