# Generated by Django 5.0.7 on 2025-11-11 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_Api', '0005_remove_labtestrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtestrequest',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('completed', 'Completed')], default='requested', max_length=20),
        ),
    ]
