# Generated by Django 5.0.7 on 2025-11-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital_Api', '0006_labtestrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='doctors/'),
        ),
    ]
