from django.urls import path
from .views import *
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('signuppage/', signup_page, name="signuppage"),
    path('auth/google/', GoogleLoginApi.as_view(), name="google_login"),
    path('LoginPage/',login_page, name="LoginPage"),
    path('logoutpage/',logout_page, name="logoutpage"),
    path("logout/", Logout, name="logout"),
    path('getuser/<int:pk>/',get_user,name='getuser'),
    path('dashboard/',dashboard_page,name='dashboard'),
    path('signup/',H_User_Signup,name='signup'),
    path('login/',Login,name='login'),
    path('sign/',doctor_signup,name='sign'),
    path('log/',doctor_login,name='log'),
    path('countdoctor/',doctor_count,name='countdoctor'),
    path('dctr_create/',Doctor_Create_Api,name='dctr'),
    path("ai/symptoms/", ai_symptom_checker),
    path('dctrs/<int:pk>/',Doctor_list,name='dctrs'),
    path('dctro/',doctor_list,name='dctro'),
    path('dotr/<int:pk>/',doctor_update_Api,name='dotr'),
    path('doctor/<int:pk>/',Doctor_delete_APi,name='doctor'),
    path('countpatient/',patient_count,name='countpatient'),
    path('patient/<int:pk>/',Patient_list,name='patient'),
    path('patientslistpage/', patients_page, name='patients_page'),
    path('pati/',patient_Api,name='pati'),
    path('patient/',Patient_Create_Api,name='patient_create'),
    path('countappointment/',appointment_count,name='countappointment'),
    path('appit/<int:pk>/',Appointment_list,name='appoit'),
    path('appoin/',Appoitment_list_Api,name='appoin'),
    path('appointmentslistpage/', appointments_page, name='appointments_page'),
    path('bookappoit/',book_appointment,name='bookappoint'),
    path("ai-symptom-checker/", ai_symptom_checker),
    path("voice/assistant/", VoiceAssistantAPI.as_view()),
    path("ai/recommend/", AIRecommendationAPI.as_view()),
    path("ai/recommend-doctor/", ai_recommend_doctor),
    path('doctorslist/', doctor_list),
    path("doctors/", doctor_page, name="doctor_page"),
    path('appoint/',Appointment_Create_Api,name='appoint'),
    path('apoit/<int:pk>/',Appointment_Update_Api,name='apoit'),
    path('apott/<int:pk>/',Appointment_Delete_Api,name='apott'),
    path('medical/<int:pk>/',MedicalRecord_list_Api,name='medical'),
    path('medicl/',Medical_list_Api,name='medicl'),
    path('medi/',MedicalRecord_create_Api,name='medi'),
    path('medil/<int:pk>/',MedicalRecord_update_Api,name='medil'),
    path('media/<int:pk>/',MedicalRecord_delete_Api,name='media'),
    path('medicine/<int:pk>/',Medicine_List_Api,name='medicine'),
    path('medicine/',Medicine_Api,name='medicines'),
    path('medicne/',Medicine_Create_Api,name='medicne'),
    path('medicin/<int:pk>/',Medicine_Update_Api,name='medicin'),
    path('medin/<int:pk>/',Medicine_Delete_Api,name='medin'),
    path('bill/<int:pk>/',Billing_List_Api,name='bill'),
    path('bills/', Billing_APi_List,name='bills'),
    path('billing/',Billing_Create_Api,name='billing'),
    path('bils/<int:pk>/',Billing_update_Api,name='bils'),
    path('billin/<int:pk>/',Billing_Delete_Api,name='billin'),
    path('countroom/',room_count,name='countroom'),
    path('room/<int:pk>/',Patient_Room_Api,name='room'),
    path('roomlist/', Patient_Room_List_Api, name='roomlist'),
    path('patientrooms/', patientroom_page, name='patientrooms'),
    path('rooms/',Patient_Room_Create_Api,name='rooms'),
    path('rom/<int:pk>/',Patient_Room_update_Api,name='rom'),
    path('roms/<int:pk>/',Patient_Room_Delete_Api,name='roms'),
    path('roomadmission/<int:pk>/',Patient_Room_Admission_List_Api,name='roomadmission'),
    path('roomadmision/',Patient_Admission_Room_Api,name='roomadmision'),
    path('roomAdmission/',Patient_Room_Admission_Create_Api,name='roomAdmission'),
    path('roomadmis/<int:pk>/',Patient_Admission_Room_update_Api,name='roomadmis'),
    path('patientroomad/<int:pk>/',Patient_Admission_Room_Delete_Api,name='patientroomad'),
    path('lab/<int:pk>/',Patient_LabTest_Api,name='lab'),
    path('labtest/',Patient_LabTest_List_Api,name='labtest'),
    path("labtests/", labtests_page,name='labtests'),
    path('labTest/',Patient_LabTest_Create_Api,name='labTest'),
    path('labtt/<int:pk>/',Patient_Lab_Test_update_Api,name='labtt'),
    path('labtestd/<int:pk>/',Patient_LabTest_Delete_Api,name='labtestd'),
    path('labrec/<int:pk>/',LabTest_Request_Api,name='labrec'),
    path('labtestreq/', Lab_Request_List_Api,name='labtestreq'),
    path('labrecord/',Lab_Test_request_Create_Api,name='labrecord'),
    path('labrecordupdate/<int:pk>/',Lab_Test_Request_Update_Api,name='labrecordupdate'),
    path('labtestrecord/<int:pk>/',Lab_Test_Request_Delete_Api,name='labtestrecord'),
    path('labres/<int:pk>/',Patient_Lab_Result_Api,name='labres'),
    path('labresult/',Patient_lab_Result_List_Api,name='labresult'),
    path('Labresult/',Patient_Lab_Result_Create_Api,name='Labresult'),
    path('labress/<int:pk>/',Patient_Lab_result_update_Api,name='labress'),
    path('labresults/<int:pk>/',Patient_Lab_Result_Delete_Api,name='labresults'),
    path('nurse/<int:pk>/',Hospital_Nurse_Staff_Api,name='nurse_detail'),
    path("nursestaffs/", nurselist_page,name='nursestaff'),
    path('nurse/',Hospital_Nurse_Staff_List_Api,name='nurse_list'),
    path('nursestaff/',Hospital_Nurse_Staff_Create_Api,name='nursestaff_create'),
    path('nursestaf/<int:pk>/',Hospital_Nurse_Staff_Update_Api,name='nursestaff_update'),
    path('nursestaffdelete/<int:pk>/',Hospital_nurse_Staff_Delete_Api,name='nursestaffdelete'),
    path('nurseduty/<int:pk>/',Hospital_Nurse_Duty_log_Api,name='nurseduty'),
    path('nursedutys/',Hospital_Nurse_Duty_Log_List_Api,name='nursedutys'),
    path('nursedutylog/',Hospital_Nurse_Duty_Create_Api,name='nursedutylog'),
    path('nursestaffupdate/<int:pk>/',Hospital_Nurse_Duty_Update_Api,name='nursestaffupdate'),
    path('nursedutydelete/<int:pk>/',Hospital_Nurse_Duty_Log_Delete_Api,name='nursedutydelete'),
    path('payment/<int:pk>/',Hospital_Payment_Api,name='payment'),
    path('paymentlist/',Hospital_Payment_List_Api,name='paymentlist'),
    path('paymentcreate/',Hospital_Payment_Create_Api,name='paymentcreate'),
    path('paymentupdate/<int:pk>/',Hospital_Payment_Update_Api,name='paymentupdaye'),
    path('paymentdelete/<int:pk>/',Hospital_Payment_Delete_Api,name='paymentdelete'),
    
    # --- Auth & OTP & Password ---
    path('auth/otp/request/', Send_OTP_Api, name='send_otp'),
    path('auth/otp/verify/', Verify_OTP_Api, name='verify_otp'),
    path('auth/password/forgot/', ForgotPassword_Api, name='forgot_password'),
    path('auth/password/reset/', ResetPassword_Api, name='reset_password'),
    path('auth/password/change/', ChangePassword_Api, name='change_password'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)